<<<<<<< HEAD

# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_tpcdi'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_tpcdi'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
=======
---

name: 'dbsql_dbt_tpch'
version: '1.0.0'
config-version: 2

profile: 'sql_endpoints'

vars:
  scalefactor: 10
  benchmark: 10
  stage: stagename
  stagingschema: rstpcdi11stg
  bucketname: bucketname  # bigquery, redshift only
  storageaccountname: synapsemigrationdemoadls
  catalog: hive_metastore
  prodschema: rstpcdi11prod

model-paths: ["Databricks/models/main"]
>>>>>>> fd9accdd82af8535c136a834748a6de529460433
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

<<<<<<< HEAD
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  dbt_tpcdi:
    example:
      +materialized: table
    bronze:
      +schema: bronze
      +materialized: table
    silver:
      +schema: silver
      +materialized: table
    gold:
      +schema: gold
      +materialized: table
    work:
      +schema: work
      +materialized: view
=======
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['dbsql_dbt_tpch', 'dbt_utils']
>>>>>>> fd9accdd82af8535c136a834748a6de529460433
