dbt_tpcdi:
  outputs:
    dev:
      dataset: TPC_SF10_STG
      job_execution_timeout_seconds: 200
      job_retries: 1
      keyfile: C:\Users\MohanavelSeshachalam\bigquery\service_key_wav\tpc-analysis-8f2c1a3a451c.json
      location: US
      method: service-account
      priority: interactive
      project: tpc-analysis
      threads: 25
      type: bigquery
  target: dev

