dbt_tpcdi:
  outputs:
    dev:
      dataset: TPC_SF10_STG
      job_execution_timeout_seconds: 200
      job_retries: 1
      keyfile: C:\Users\MohanavelSeshachalam\bigquery\service_key\bq-benchmark-unit-6af180708118.json
      location: US
      method: service-account
      priority: interactive
      project: bq-benchmark-unit
      threads: 25
      type: bigquery
  target: dev

