---

version: 2

jobs:
  build:
    docker:
      - image: cimg/python:3.9.9

    steps:
      - checkout

      - run:
          name: setup_creds
          command: |
            echo $BIGQUERY_SERVICE_ACCOUNT_JSON > ${HOME}/bigquery-service-key.json

      - restore_cache:
          key: deps1-{{ .Branch }}

      - run:
          name: "Setup dbt"
          command: |
            set -x

            python -m venv dbt_venv
            . dbt_venv/bin/activate

            python -m pip install --upgrade pip setuptools
            python -m pip install --pre dbt-core dbt-postgres dbt-redshift dbt-snowflake dbt-bigquery

            mkdir -p ~/.dbt
            cp integration_tests/ci/sample.profiles.yml ~/.dbt/profiles.yml

      - run:
          name: "Run Tests - Redshift"
          command: |
            . dbt_venv/bin/activate
            echo `pwd`
            cd Redshift/integration_tests
            dbt deps --target redshift
            dbt seed --target redshift --full-refresh
            dbt compile --target redshift
            dbt run --target redshift
            dbt test --target redshift

      - run:
          name: "Run Tests - Databricks"
          command: |
            . dbt_venv/bin/activate
            echo `pwd`
            cd Databricks/integration_tests
            dbt deps --target databricks
            dbt seed --target databricks --full-refresh
            dbt compile --target databricks
            dbt run --target databricks
            dbt test --target databricks

      - run:
          name: "Run Tests - Snowflake"
          command: |
            . dbt_venv/bin/activate
            echo `pwd`
            cd Snowflake/integration_tests
            dbt deps --target snowflake
            dbt seed --target snowflake --full-refresh
            dbt compile --target snowflake
            dbt run --target snowflake
            dbt test --target snowflake

      - run:
          name: "Run Tests - BigQuery"
          environment:
            BIGQUERY_SERVICE_KEY_PATH: "/home/circleci/bigquery-service-key.json"

          command: |
            . dbt_venv/bin/activate
            echo `pwd`
            cd BigQuery/integration_tests
            dbt deps --target bigquery
            dbt seed --target bigquery --full-refresh
            dbt compile --target bigquery
            dbt run --target bigquery --full-refresh
            dbt test --target bigquery


      - save_cache:
          key: deps1-{{ .Branch }}
          paths:
            - "dbt_venv"


      - store_artifacts:
          path: integration_tests/logs
      - store_artifacts:
          path: integration_tests/target

workflows:
  version: 2
  test-all:
    jobs:
      - build:
          context:
            - profile-redshift
            - profile-snowflake
            - profile-bigquery
            - profile-databricks
