version: 2

sources:
  - name: brokerage
    database: tpc-analysis
    schema: TPC_SF10_STG   


    tables:
      - name: DAILY_MARKET
      - name: WATCH_HISTORY
      - name: TRADE
      - name: TRADE_HISTORY
      - name: HOLDING_HISTORY
      - name: CASH_TRANSACTION
      
